spring:
  application:
    name: scale
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://ep-quiet-sea-b2c8ifbd-pooler.c-6.eu-central-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require}
    username: ${SPRING_DATASOURCE_USERNAME:neondb_owner}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  security:
    oauth2:
      client:
        registration:
          google:
            redirect-uri: "https://cloud.bilch.eu/login/oauth2/code/google"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    env:
      show-values: always

logging:
  level:
    '[eu.bilch.scale]': info
